# Change these first
owner: SpecializedBicycles # Your GitHub organization or username, where this repository lives
repo: retul-uptime-monitor # The name of this repository

sites:
  - name: Premium Fit Admin Page
    url: https://api.production.retul.com/premium-fit-service/admin/login/?next=/premium-fit-service/admin/
  - name: Bike Sizing Service Admin Page
    url: https://api.production.retul.com/bike-sizing-service/admin/login/?next=/bike-sizing-service/admin/
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /retul-uptime-monitor
  name: Retül
  apiBaseUrl: https://api.github.com


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
